
spring:

  liquibase:
    enabled: true
    # Добавляем тестовые данные , sampleData
    contexts: develop , sampleData
  application:
    name: todospringptoject
  datasource:
    url: jdbc:mysql://localhost:3306/todo_spring?useUnicode=true&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        generate_statistics: true
        jdbc.batch_size: 100

logging:
  level:
    org:
      hibernate.engine.internal.StatisticalLoggingSessionEventListener: INFO
      springframework.transaction: TRACE
      springframework.transaction.support: TRACE


#  spring.application.name=todospringptoject
#  spring.jpa.hibernate.ddl-auto=update
#  spring.datasource.url=jdbc:mysql://localhost:3306/todo_spring?useUnicode=true&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#  spring.datasource.username=root
#  spring.datasource.password=root
