
spring:
  liquibase:
    enabled: true
  application:
    name: todospringptoject
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/todo_spring?useUnicode=true&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root


#  spring.application.name=todospringptoject
#  spring.jpa.hibernate.ddl-auto=update
#  spring.datasource.url=jdbc:mysql://localhost:3306/todo_spring?useUnicode=true&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#  spring.datasource.username=root
#  spring.datasource.password=root
